CREATE TABLE ORDENCOMPRA
(
  OCNRO             VARCHAR(15)            NOT NULL,
  REFERENCIA        VARCHAR(250),
  SOLICITANTE       VARCHAR(100),
  PROYECTOID        INT(2)                    NOT NULL,
  FECHAOC           DATE,
  FECHAIMP          DATE,
  TOTALOC           DECIMAL(10,2),
  ALMDIR            VARCHAR(200),
  OBSERVACION       TEXT,
  OCESTADO          CHAR(1)                NOT NULL,
  OCPREIMPRESOINI   VARCHAR(15),
  COTPROVID         VARCHAR(10),
  TOTALIGV          DECIMAL(10,2),
  TIPOORDEN         CHAR(1)                NOT NULL,
  FACTURA           VARCHAR(200),
  GUIA_DE_REMISION  TEXT  
);

CREATE TABLE ORDENSERVICIO
(
  OSNRO            VARCHAR(15)            NOT NULL,
  OSPREIMPRESOINI  VARCHAR(15),
  REFERENCIA       VARCHAR(250),
  SOLICITANTE      VARCHAR(100),
  PROYECTOID       INT(2)                      NOT NULL,
  FECHAOS          DATE,
  FECHAIMP         DATE,
  TOTALOS          DECIMAL(10,2),
  OBSERVACION      TEXT,
  OSESTADO         CHAR(1)                 NOT NULL,
  COTPROVID        VARCHAR(10),
  TOTALIGV         DECIMAL(10,2),
  TIPOORDEN        CHAR(1)                 NOT NULL
);

CREATE TABLE PECOSA
(
  PECNRO             INT(15),
  PROYECTOID         INT(2),
  PECOBS             TEXT,
  PECMONTOT          DECIMAL(10,2),
  PECESTADO          CHAR(1),
  OCNRO              VARCHAR(15)          NOT NULL,
  PECDES             VARCHAR(200),
  PECDESDIR          VARCHAR(200),
  PREIMPRESOINICIAL  VARCHAR(15),
  SERIE              TEXT,
  FECHAPEC           DATE
);

CREATE TABLE DETALLEOC
(
  DETOCID     INT(10)                            NOT NULL,
  ESPECIFICA  VARCHAR(15),
  IMPUESTO    CHAR(1),
  ARTCOD      VARCHAR(10),
  MARCA       VARCHAR(50),
  MONEDA      CHAR(1),
  CANTIDAD    INT(10),
  PRECIOUNIT  DECIMAL(10,2),
  TIPOPRECIO  CHAR(1),
  OCNRO       VARCHAR(10)                 NOT NULL,
  SUBTOTAL    DECIMAL(10,2),
  IGV         DECIMAL(10,2),
  ARTDES      VARCHAR(200),
  DETALLE     VARCHAR(200),
  PROYECTOID  INT(2)                           NOT NULL,
  UNIDMED     VARCHAR(10)
);

CREATE TABLE DETALLEOS
(
  DETOSID     INT(10)                            NOT NULL,
  ESPECIFICA  VARCHAR(10),
  IMPUESTO    CHAR(1),
  ARTCOD      VARCHAR(10),
  MONEDA      CHAR(1),
  PRECIOUNIT  DECIMAL(10,2),
  TIPOPRECIO  CHAR(1),
  OSNRO       VARCHAR(10)                        NOT NULL,
  IGV         DECIMAL(10,2),
  SUBTOTAL    DECIMAL(10,2),
  DETALLE     VARCHAR(200),
  PROYECTOID  INT(2)                            NOT NULL,
  ARTDES      VARCHAR(200)
);

CREATE TABLE COTIZACIONPROVEEDOR
(
  COTPROVID      VARCHAR(10)              NOT NULL,
  RUC            VARCHAR(11)              NOT NULL,
  DETALLECOT     VARCHAR(250),
  PRODIR         VARCHAR(200),
  RAZONSOCIAL    VARCHAR(200)             NOT NULL,
  PROTEL         VARCHAR(20),
  GARANTIA       VARCHAR(200),
  FORMAPAGO      VARCHAR(200),
  TIEMPOENTREGA  VARCHAR(200),
  TIPOORDEN      CHAR(1)                   NOT NULL
);

CREATE TABLE USUARIO_FINZYT
(
  ID          INT(5)                            NOT NULL,
  USUNOM      VARCHAR(30),
  PASSWORD    VARCHAR(30),
  ESTADO      INT(1),
  PROYECTOID  INT(2)                            NOT NULL,
  ROL         VARCHAR(30),
  EMAIL       VARCHAR(50)
);

ALTER TABLE ORDENCOMPRA ADD (
  CONSTRAINT ORDENCOMPRA_PK
 PRIMARY KEY
 (OCNRO, PROYECTOID));

ALTER TABLE ORDENSERVICIO ADD (
  CONSTRAINT ORDENSERVICIO_PK
 PRIMARY KEY
 (OSNRO, PROYECTOID));

ALTER TABLE PECOSA ADD (
  CONSTRAINT PECOSA_PK
 PRIMARY KEY
 (PECNRO, PROYECTOID));

ALTER TABLE DETALLEOC ADD (
  PRIMARY KEY
 (DETOCID, PROYECTOID));

ALTER TABLE DETALLEOS ADD (
  CONSTRAINT DETALLEOS_PK
 PRIMARY KEY
 (DETOSID, PROYECTOID));

ALTER TABLE COTIZACIONPROVEEDOR ADD (
  CONSTRAINT COTIZACIONPROVEEDOR_PK
 PRIMARY KEY
 (COTPROVID, TIPOORDEN));

ALTER TABLE USUARIO_FINZYT ADD (
  CONSTRAINT USUARIO_FINZYT_PK
 PRIMARY KEY
 (ID));


 ALTER TABLE ORDENCOMPRA ADD (
  CONSTRAINT OC_COTPROV_FK 
 FOREIGN KEY (COTPROVID, TIPOORDEN) 
 REFERENCES COTIZACIONPROVEEDOR (COTPROVID,TIPOORDEN));

ALTER TABLE ORDENSERVICIO ADD (
  CONSTRAINT OS_COTPROV_FK 
 FOREIGN KEY (COTPROVID, TIPOORDEN) 
 REFERENCES COTIZACIONPROVEEDOR (COTPROVID,TIPOORDEN));

ALTER TABLE PECOSA ADD (
  CONSTRAINT OC_PECOSA_FK 
 FOREIGN KEY (OCNRO, PROYECTOID) 
 REFERENCES ORDENCOMPRA (OCNRO,PROYECTOID));

ALTER TABLE DETALLEOC ADD (
  CONSTRAINT DETALLEOC_FK 
 FOREIGN KEY (OCNRO, PROYECTOID) 
 REFERENCES ORDENCOMPRA (OCNRO,PROYECTOID));

ALTER TABLE DETALLEOS ADD (
  CONSTRAINT DETALLEOS_FK 
 FOREIGN KEY (OSNRO, PROYECTOID) 
 REFERENCES ORDENSERVICIO (OSNRO,PROYECTOID));