package pe.edu.unmsm.quipucamayoc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo implements java.io.Serializable {

	private String artcod;
	private String artdes;

	public Articulo() {
	}

	public Articulo(String artcod) {
		this.artcod = artcod;
	}

	public Articulo(String artcod, String artdes) {
		this.artcod = artcod;
		this.artdes = artdes;
	}

	public String getArtcod() {
		return this.artcod;
	}

	public void setArtcod(String artcod) {
		this.artcod = artcod;
	}

	public String getArtdes() {
		return this.artdes;
	}

	public void setArtdes(String artdes) {
		this.artdes = artdes;
	}

}
