// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
/**
 * CotizacionproveedorId generated by hbm2java
 */
public class CotizacionproveedorId implements java.io.Serializable {

	private String cotprovid;
	private char tipoorden;

	public CotizacionproveedorId() {
	}

	public CotizacionproveedorId(String cotprovid, char tipoorden) {
		this.cotprovid = cotprovid;
		this.tipoorden = tipoorden;
	}

	public String getCotprovid() {
		return this.cotprovid;
	}

	public void setCotprovid(String cotprovid) {
		this.cotprovid = cotprovid;
	}

	public char getTipoorden() {
		return this.tipoorden;
	}

	public void setTipoorden(char tipoorden) {
		this.tipoorden = tipoorden;
	}
}
