// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacionproveedor generated by hbm2java
 */
public class Cotizacionproveedor implements java.io.Serializable {

	private CotizacionproveedorId id;
	private String ruc;
	private String detallecot;
	private String prodir;
	private String razonsocial;
	private String protel;
	private String garantia;
	private String formapago;
	private String tiempoentrega;
	private Set ordencompras = new HashSet(0);
	private Set ordenservicios = new HashSet(0);

	public Cotizacionproveedor() {
	}

	public Cotizacionproveedor(CotizacionproveedorId id, String ruc,
			String razonsocial) {
		this.id = id;
		this.ruc = ruc;
		this.razonsocial = razonsocial;
	}

	public Cotizacionproveedor(CotizacionproveedorId id, String ruc,
			String detallecot, String prodir, String razonsocial,
			String protel, String garantia, String formapago,
			String tiempoentrega, Set ordencompras, Set ordenservicios) {
		this.id = id;
		this.ruc = ruc;
		this.detallecot = detallecot;
		this.prodir = prodir;
		this.razonsocial = razonsocial;
		this.protel = protel;
		this.garantia = garantia;
		this.formapago = formapago;
		this.tiempoentrega = tiempoentrega;
		this.ordencompras = ordencompras;
		this.ordenservicios = ordenservicios;
	}

	public CotizacionproveedorId getId() {
		return this.id;
	}

	public void setId(CotizacionproveedorId id) {
		this.id = id;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public String getDetallecot() {
		return this.detallecot;
	}

	public void setDetallecot(String detallecot) {
		this.detallecot = detallecot;
	}

	public String getProdir() {
		return this.prodir;
	}

	public void setProdir(String prodir) {
		this.prodir = prodir;
	}

	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	public String getProtel() {
		return this.protel;
	}

	public void setProtel(String protel) {
		this.protel = protel;
	}

	public String getGarantia() {
		return this.garantia;
	}

	public void setGarantia(String garantia) {
		this.garantia = garantia;
	}

	public String getFormapago() {
		return this.formapago;
	}

	public void setFormapago(String formapago) {
		this.formapago = formapago;
	}

	public String getTiempoentrega() {
		return this.tiempoentrega;
	}

	public void setTiempoentrega(String tiempoentrega) {
		this.tiempoentrega = tiempoentrega;
	}

	public Set getOrdencompras() {
		return this.ordencompras;
	}

	public void setOrdencompras(Set ordencompras) {
		this.ordencompras = ordencompras;
	}

	public Set getOrdenservicios() {
		return this.ordenservicios;
	}

	public void setOrdenservicios(Set ordenservicios) {
		this.ordenservicios = ordenservicios;
	}

}
