// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
import java.math.BigDecimal;
import java.math.RoundingMode;

import javax.faces.event.ValueChangeEvent;

/**
 * Detalleos generated by hbm2java
 */
public class Detalleos implements java.io.Serializable {

	private DetalleosId id;
	private Ordenservicio ordenservicio;
	private String especifica;
	private Character impuesto;
	private String artcod;
	private String artdes;
	private char moneda;
	private char tipoprecio;
	private BigDecimal preciounit;
	private BigDecimal igv;
	private BigDecimal subtotal;
	private String detalle;
	private String osnro;

	public Detalleos() {
	}

	public Detalleos(DetalleosId id, Ordenservicio ordenservicio) {
		this.id = id;
		this.ordenservicio = ordenservicio;
	}

	public Detalleos(DetalleosId id, Ordenservicio ordenservicio,
			String especifica, Character impuesto, String artcod,
			char moneda, BigDecimal preciounit, char tipoprecio,
			BigDecimal igv, BigDecimal subtotal, String detalle) {
		this.id = id;
		this.ordenservicio = ordenservicio;
		this.especifica = especifica;
		this.impuesto = impuesto;
		this.artcod = artcod;
		this.moneda = moneda;
		this.preciounit = preciounit;
		this.tipoprecio = tipoprecio;
		this.igv = igv;
		this.subtotal = subtotal;
		this.detalle = detalle;
	}

	public DetalleosId getId() {
		return this.id;
	}

	public void setId(DetalleosId id) {
		this.id = id;
	}

	public Ordenservicio getOrdenservicio() {
		return this.ordenservicio;
	}

	public void setOrdenservicio(Ordenservicio ordenservicio) {
		this.ordenservicio = ordenservicio;
	}

	public String getEspecifica() {
		return this.especifica;
	}

	public void setEspecifica(String especifica) {
		this.especifica = especifica;
	}

	public Character getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(Character impuesto) {
		this.impuesto = impuesto;
	}

	public String getArtcod() {
		return this.artcod;
	}

	public void setArtcod(String artcod) {
		this.artcod = artcod;
	}

	public char getMoneda() {
		return this.moneda;
	}

	public void setMoneda(char moneda) {
		this.moneda = moneda;
	}

	public BigDecimal getPreciounit() {
		return this.preciounit;
	}

	public void setPreciounit(BigDecimal preciounit) {
		this.preciounit = preciounit;
	}

	public char getTipoprecio() {
		return this.tipoprecio;
	}

	public void setTipoprecio(char tipoprecio) {
		this.tipoprecio = tipoprecio;
	}

	public BigDecimal getIgv() {
		return this.igv;
	}

	public void setIgv(BigDecimal igv) {
		this.igv = igv;
	}

	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getArtdes() {
		return artdes;
	}

	public void setArtdes(String artdes) {
		this.artdes = artdes;
	}

	public String getOsnro() {
		return osnro;
	}

	public void setOsnro(String osnro) {
		this.osnro = osnro;
	}

	/*Funciones Adicionales*/
	public void calcularMontoEnFuncionDeSeleccionIGV(ValueChangeEvent event){
		//Calcula segun la seleccion del desplegable Elija impuesto.
		BigDecimal MontoSinIGV = new BigDecimal("0.00");
		if(this.getPreciounit()!=null){
			MontoSinIGV = this.getPreciounit();
			Character valor = (Character)event.getNewValue();
			BigDecimal conIgvAdicional = new BigDecimal("1.18");
			BigDecimal igv = new BigDecimal("0.18");
			if(valor=='2'){
				BigDecimal auxMonto = redondearIGV(MontoSinIGV.multiply(conIgvAdicional));
				BigDecimal auxIGV = redondearIGV(MontoSinIGV.multiply(igv));
				this.setImpuesto('2');
				this.setIgv(auxIGV);
				this.setSubtotal(auxMonto);
			} else if(valor=='1'){
				BigDecimal aux = MontoSinIGV;
				BigDecimal auxMonto = redondearIGV(aux.divide(conIgvAdicional,9,RoundingMode.HALF_UP));
				BigDecimal auxIGV = redondearIGV(auxMonto.multiply(igv));
				MontoSinIGV = redondearIGV(MontoSinIGV);
				this.setImpuesto('1');
				this.setIgv(auxIGV);
				this.setSubtotal(MontoSinIGV);			
			}			
		}		
	}
	
	public void  calcularMontoEnFuncionDePrecioUnit(ValueChangeEvent event){
		//Calcula segun la inserción de montos en las cajas de texto precio unitario.
		BigDecimal MontoSinIGV = new BigDecimal("0.00");
		if(this.getPreciounit()!=null){
			BigDecimal valor=(BigDecimal)event.getNewValue();			
			MontoSinIGV = valor;			
			BigDecimal conIgvAdicional = new BigDecimal("1.18");
			BigDecimal igv = new BigDecimal("0.18");
			if(this.impuesto=='2'){
				BigDecimal auxMonto = redondearIGV(MontoSinIGV.multiply(conIgvAdicional));
				BigDecimal auxIGV = redondearIGV(MontoSinIGV.multiply(igv));
				this.setImpuesto('2');
				this.setIgv(auxIGV);
				this.setSubtotal(auxMonto);
			} else if(this.impuesto=='1'){
				BigDecimal aux = MontoSinIGV;
				BigDecimal auxMonto = redondearIGV(aux.divide(conIgvAdicional,9,RoundingMode.HALF_UP));
				BigDecimal auxIGV = redondearIGV(auxMonto.multiply(igv));
				MontoSinIGV = redondearIGV(MontoSinIGV);
				this.setImpuesto('1');
				this.setIgv(auxIGV);
				this.setSubtotal(MontoSinIGV);			
			}			
		}				
		
	}
	private BigDecimal redondearIGV(BigDecimal igv){
		
		BigDecimal redondeado =igv.setScale(2, BigDecimal.ROUND_HALF_UP);		
		return redondeado;
	}
	
	public boolean convertImpuestoToBoolean(){
		if(this.impuesto == '1'){
			return true;
		}		
		else if(this.impuesto == '2'){
			return false;
		}else{
			return false;
		}
	}	
}
