// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordencompra generated by hbm2java
 */
public class Ordencompra implements java.io.Serializable {

	private OrdencompraId id;
	private Cotizacionproveedor cotizacionproveedor;
	private String referencia;
	private String solicitante;
	private Date fechaoc;
	private Date fechaimp;
	private BigDecimal totaloc;
	private String almdir;
	private String observacion;
	private String ocestado;	
	private String ocpreimpresoini;
	private BigDecimal totaligv;	
	private String factura;
	private String guiaDeRemision;
	private Set pecosas = new HashSet(0);
	private Set<Detalleoc> detalleocs = new HashSet<Detalleoc>();

	public Ordencompra() {
	}

	public Ordencompra(OrdencompraId id,
			Cotizacionproveedor cotizacionproveedor, String ocestado) {
		this.id = id;
		this.cotizacionproveedor = cotizacionproveedor;
		this.ocestado = ocestado;
	}

	public Ordencompra(OrdencompraId id,
			Cotizacionproveedor cotizacionproveedor, String referencia,
			String solicitante, Date fechaoc, Date fechaimp,
			BigDecimal totaloc, String almdir, String observacion,
			String ocestado, String ocpreimpresoini, BigDecimal totaligv,
			String factura, String guiaDeRemision, Set pecosas,Set detalleocs) {
		this.id = id;
		this.cotizacionproveedor = cotizacionproveedor;
		this.referencia = referencia;
		this.solicitante = solicitante;
		this.fechaoc = fechaoc;
		this.fechaimp = fechaimp;
		this.totaloc = totaloc;
		this.almdir = almdir;
		this.observacion = observacion;
		this.ocestado = ocestado;
		this.ocpreimpresoini = ocpreimpresoini;
		this.totaligv = totaligv;
		this.factura = factura;
		this.guiaDeRemision = guiaDeRemision;
		this.pecosas = pecosas;
		this.detalleocs = detalleocs;
	}

	public OrdencompraId getId() {
		return this.id;
	}

	public void setId(OrdencompraId id) {
		this.id = id;
	}

	public Cotizacionproveedor getCotizacionproveedor() {
		return this.cotizacionproveedor;
	}

	public void setCotizacionproveedor(Cotizacionproveedor cotizacionproveedor) {
		this.cotizacionproveedor = cotizacionproveedor;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	public Date getFechaoc() {
		return this.fechaoc;
	}

	public void setFechaoc(Date fechaoc) {
		this.fechaoc = fechaoc;
	}

	public Date getFechaimp() {
		return this.fechaimp;
	}

	public void setFechaimp(Date fechaimp) {
		this.fechaimp = fechaimp;
	}

	public BigDecimal getTotaloc() {
		return this.totaloc;
	}

	public void setTotaloc(BigDecimal totaloc) {
		this.totaloc = totaloc;
	}

	public String getAlmdir() {
		return this.almdir;
	}

	public void setAlmdir(String almdir) {
		this.almdir = almdir;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getOcestado() {
		return ocestado;
	}

	public void setOcestado(String ocestado) {
		this.ocestado = ocestado;
	}

	public String getOcpreimpresoini() {
		return this.ocpreimpresoini;
	}

	public void setOcpreimpresoini(String ocpreimpresoini) {
		this.ocpreimpresoini = ocpreimpresoini;
	}

	public BigDecimal getTotaligv() {
		return this.totaligv;
	}

	public void setTotaligv(BigDecimal totaligv) {
		this.totaligv = totaligv;
	}

	public Set<Detalleoc> getDetalleocs() {
		return this.detalleocs;
	}

	public void setDetalleocs(Set<Detalleoc> detalleocs) {
		this.detalleocs = detalleocs;
	}

	public String getFactura() {
		return factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getGuiaDeRemision() {
		return guiaDeRemision;
	}

	public void setGuiaDeRemision(String guiaDeRemision) {
		this.guiaDeRemision = guiaDeRemision;
	}

	public Set getPecosas() {
		return pecosas;
	}

	public void setPecosas(Set pecosas) {
		this.pecosas = pecosas;
	}
	
	@Override
	public String toString() {
		return "Ordencompra [id=" + id + ", cotizacionproveedor="
				+ cotizacionproveedor + ", referencia=" + referencia
				+ ", solicitante=" + solicitante + ", fechaoc=" + fechaoc
				+ ", fechaimp=" + fechaimp + ", totaloc=" + totaloc
				+ ", almdir=" + almdir + ", observacion=" + observacion
				+ ", ocestado=" + ocestado + ", ocpreimpresoini="
				+ ocpreimpresoini + ", totaligv=" + totaligv + ", factura="
				+ factura + ", guiaDeRemision=" + guiaDeRemision + ", pecosas="
				+ pecosas + ", detalleocs=" + detalleocs + "]";
	}

}
