// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;


/**
 * OrdenservicioId generated by hbm2java
 */
public class OrdenservicioId implements java.io.Serializable {

	private String osnro;
	private int proyectoid;

	public OrdenservicioId() {
	}

	public OrdenservicioId(String osnro, int proyectoid) {
		this.osnro = osnro;
		this.proyectoid = proyectoid;
	}

	public String getOsnro() {
		return this.osnro;
	}

	public void setOsnro(String osnro) {
		this.osnro = osnro;
	}

	public int getProyectoid() {
		return this.proyectoid;
	}

	public void setProyectoid(int proyectoid) {
		this.proyectoid = proyectoid;
	}

}
