// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;


/**
 * OrdencompraId generated by hbm2java
 */
public class OrdencompraId implements java.io.Serializable {

	private String ocnro;
	private int proyectoid;

	public OrdencompraId() {
	}

	public OrdencompraId(String ocnro, int proyectoid) {
		this.ocnro = ocnro;
		this.proyectoid = proyectoid;
	}

	public String getOcnro() {
		return this.ocnro;
	}

	public void setOcnro(String ocnro) {
		this.ocnro = ocnro;
	}

	public int getProyectoid() {
		return this.proyectoid;
	}

	public void setProyectoid(int proyectoid) {
		this.proyectoid = proyectoid;
	}

}
