// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenservicio generated by hbm2java
 */
public class Ordenservicio implements java.io.Serializable {

	private OrdenservicioId id;
	private Cotizacionproveedor cotizacionproveedor;
	private String ospreimpresoini;
	private String referencia;
	private String solicitante;
	private Date fechaos;
	private Date fechaimp;
	private BigDecimal totalos;
	private String observacion;
	private String osestado;
	private String cotprovid;
	private BigDecimal totaligv;
	private Set<Detalleos> detalleoses = new HashSet<Detalleos>();

	public Ordenservicio() {
	}

	public Ordenservicio(OrdenservicioId id,
			Cotizacionproveedor cotizacionproveedor, String osestado) {
		this.id = id;
		this.cotizacionproveedor = cotizacionproveedor;
		this.osestado = osestado;
	}

	public Ordenservicio(OrdenservicioId id,
			Cotizacionproveedor cotizacionproveedor, String ospreimpresoini,
			String referencia, String solicitante, Date fechaos, Date fechaimp,
			BigDecimal totalos, String observacion, String osestado,
			String cotprovid, BigDecimal totaligv, Set detalleoses) {
		this.id = id;
		this.cotizacionproveedor = cotizacionproveedor;
		this.ospreimpresoini = ospreimpresoini;
		this.referencia = referencia;
		this.solicitante = solicitante;
		this.fechaos = fechaos;
		this.fechaimp = fechaimp;
		this.totalos = totalos;
		this.observacion = observacion;
		this.osestado = osestado;
		this.cotprovid = cotprovid;
		this.totaligv = totaligv;
		this.detalleoses = detalleoses;
	}

	public OrdenservicioId getId() {
		return this.id;
	}

	public void setId(OrdenservicioId id) {
		this.id = id;
	}

	public Cotizacionproveedor getCotizacionproveedor() {
		return this.cotizacionproveedor;
	}

	public void setCotizacionproveedor(Cotizacionproveedor cotizacionproveedor) {
		this.cotizacionproveedor = cotizacionproveedor;
	}

	public String getOspreimpresoini() {
		return this.ospreimpresoini;
	}

	public void setOspreimpresoini(String ospreimpresoini) {
		this.ospreimpresoini = ospreimpresoini;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	public Date getFechaos() {
		return this.fechaos;
	}

	public void setFechaos(Date fechaos) {
		this.fechaos = fechaos;
	}

	public Date getFechaimp() {
		return this.fechaimp;
	}

	public void setFechaimp(Date fechaimp) {
		this.fechaimp = fechaimp;
	}

	public BigDecimal getTotalos() {
		return this.totalos;
	}

	public void setTotalos(BigDecimal totalos) {
		this.totalos = totalos;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getOsestado() {
		return this.osestado;
	}

	public void setOsestado(String osestado) {
		this.osestado = osestado;
	}

	public String getCotprovid() {
		return this.cotprovid;
	}

	public void setCotprovid(String cotprovid) {
		this.cotprovid = cotprovid;
	}

	public BigDecimal getTotaligv() {
		return this.totaligv;
	}

	public void setTotaligv(BigDecimal totaligv) {
		this.totaligv = totaligv;
	}

	public Set<Detalleos> getDetalleoses() {
		return this.detalleoses;
	}

	public void setDetalleoses(Set<Detalleos> detalleoses) {
		this.detalleoses = detalleoses;
	}

}
