package pe.edu.unmsm.quipucamayoc.model;
// default package
// Generated 21/07/2014 12:26:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pecosa generated by hbm2java
 */
public class Pecosa implements java.io.Serializable {

	private PecosaId id;
	private Ordencompra ordencompra;
	private String pecobs;
	private Double pecmontot;
	private String pecestado;
	private String pecdes;
	private String pecdesdir;
	private String preimpresoinicial;	
	private String serie;
	private Date fechapec;
	private String ocnro;//Foránea de Orden compra
	public Pecosa() {
	}

	public Pecosa(PecosaId id, Ordencompra ordencompra) {
		this.id = id;
		this.ordencompra = ordencompra;
	}

	public Pecosa(PecosaId id, Ordencompra ordencompra, String pecobs,
			Double pecmontot, String pecestado, String pecdes,
			String pecdesdir, String preimpresoinicial,String serie,Date fechapec) {
		this.id = id;
		this.ordencompra = ordencompra;
		this.pecobs = pecobs;
		this.pecmontot = pecmontot;
		this.pecestado = pecestado;
		this.pecdes = pecdes;
		this.pecdesdir = pecdesdir;
		this.preimpresoinicial = preimpresoinicial;		
		this.serie=serie;
		this.fechapec=fechapec;
	}

	public PecosaId getId() {
		return this.id;
	}

	public void setId(PecosaId id) {
		this.id = id;
	}

	public Ordencompra getOrdencompra() {
		return this.ordencompra;
	}

	public void setOrdencompra(Ordencompra ordencompra) {
		this.ordencompra = ordencompra;
	}

	public String getPecobs() {
		return this.pecobs;
	}

	public void setPecobs(String pecobs) {
		this.pecobs = pecobs;
	}

	public Double getPecmontot() {
		return this.pecmontot;
	}

	public void setPecmontot(Double pecmontot) {
		this.pecmontot = pecmontot;
	}

	public String getPecestado() {
		return this.pecestado;
	}

	public void setPecestado(String pecestado) {
		this.pecestado = pecestado;
	}

	public String getPecdes() {
		return this.pecdes;
	}

	public void setPecdes(String pecdes) {
		this.pecdes = pecdes;
	}

	public String getPecdesdir() {
		return this.pecdesdir;
	}

	public void setPecdesdir(String pecdesdir) {
		this.pecdesdir = pecdesdir;
	}

	public String getPreimpresoinicial() {
		return this.preimpresoinicial;
	}

	public void setPreimpresoinicial(String preimpresoinicial) {
		this.preimpresoinicial = preimpresoinicial;
	}

	public String getSerie() {
		return serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public Date getFechapec() {
		return fechapec;
	}

	public void setFechapec(Date fechapec) {
		this.fechapec = fechapec;
	}

	public String getOcnro() {
		return ocnro;
	}

	public void setOcnro(String ocnro) {
		this.ocnro = ocnro;
	}


}
