package pe.edu.unmsm.quipucamayoc.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

	private String proruc;	
	private String prodir;
	private String prorazsoc;
	private String protel;	
	private String proconnom;
	private String proconapepat;
	private String proconapemat;
	private Character prosit;	
	private String pronom;
	private String proapepat;
	private String proapemat;
	
	public Proveedor() {
	}

	public Proveedor(String proruc) {
		this.proruc = proruc;
	}

	public Proveedor(String proruc, String prodir,String protel,
			String prorazsoc,Character prosit,
			String proconnom,
			String proconapepat, String proconapemat,
			String pronom,
			String proapepat, String proapemat) {
		this.proruc = proruc;		
		this.prodir = prodir;
		this.prorazsoc = prorazsoc;
		this.protel = protel;		
		this.proconnom = proconnom;
		this.proconapepat = proconapepat;
		this.proconapemat = proconapemat;
		this.prosit = prosit;		
		this.pronom = pronom;
		this.proapepat = proapepat;
		this.proapemat = proapemat;		
	}

	public String getProruc() {
		return this.proruc;
	}

	public void setProruc(String proruc) {
		this.proruc = proruc;
	}
	
	public String getProdir() {
		return this.prodir;
	}

	public void setProdir(String prodir) {
		this.prodir = prodir;
	}

	public String getProrazsoc() {
		return this.prorazsoc;
	}

	public void setProrazsoc(String prorazsoc) {
		this.prorazsoc = prorazsoc;
	}


	public String getProtel() {
		return this.protel;
	}

	public void setProtel(String protel) {
		this.protel = protel;
	}

	public String getProconnom() {
		return this.proconnom;
	}

	public void setProconnom(String proconnom) {
		this.proconnom = proconnom;
	}

	public String getProconapepat() {
		return this.proconapepat;
	}

	public void setProconapepat(String proconapepat) {
		this.proconapepat = proconapepat;
	}

	public String getProconapemat() {
		return this.proconapemat;
	}

	public void setProconapemat(String proconapemat) {
		this.proconapemat = proconapemat;
	}

	public Character getProsit() {
		return this.prosit;
	}

	public void setProsit(Character prosit) {
		this.prosit = prosit;
	}

	public String getPronom() {
		return this.pronom;
	}

	public void setPronom(String pronom) {
		this.pronom = pronom;
	}

	public String getProapepat() {
		return this.proapepat;
	}

	public void setProapepat(String proapepat) {
		this.proapepat = proapepat;
	}

	public String getProapemat() {
		return this.proapemat;
	}

	public void setProapemat(String proapemat) {
		this.proapemat = proapemat;
	}

    @Override
    public String toString() {
        return "Proveedor{" + "proruc=" + proruc + ", prodir=" + prodir + ", prorazsoc=" + prorazsoc + ", protel=" + protel + ", proconnom=" + proconnom + ", proconapepat=" + proconapepat + ", proconapemat=" + proconapemat + ", prosit=" + prosit + ", pronom=" + pronom + ", proapepat=" + proapepat + ", proapemat=" + proapemat + '}';
    }
}
