// default package
// Generated 16/06/2014 05:57:43 PM by Hibernate Tools 3.4.0.CR1
package pe.edu.unmsm.quipucamayoc.model;
import java.math.BigDecimal;

/**
 * UsuarioFinzyt generated by hbm2java
 */
public class UsuarioFinzyt implements java.io.Serializable {

	private Long id;
	private String usunom;
	private String password;
	private Integer estado;
	private int proyectoid;
	private String rol;
	private String email;

	public UsuarioFinzyt() {
	}

	public UsuarioFinzyt(Long id, int proyectoid) {
		this.id = id;
		this.proyectoid = proyectoid;
	}

	public UsuarioFinzyt(Long id, String usunom, String password,
			Integer estado, int proyectoid, String rol) {
		this.id = id;
		this.usunom = usunom;
		this.password = password;
		this.estado = estado;
		this.proyectoid = proyectoid;
		this.rol = rol;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsunom() {
		return this.usunom;
	}

	public void setUsunom(String usunom) {
		this.usunom = usunom;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public int getProyectoid() {
		return this.proyectoid;
	}

	public void setProyectoid(int proyectoid) {
		this.proyectoid = proyectoid;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
